import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Автогенерация сайдбара по структуре папки docs.
// Порядок и названия берутся из front matter (sidebar_position, sidebar_label).
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
