name: "📄 Предложение"
description: Предложить новую страницу или крупное обновление раздела
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Расскажите, какую тему нужно раскрыть в wiki.
  - type: input
    id: title
    attributes:
      label: Предлагаемое название
      placeholder: Например, "Готовые портативные наборы V3"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Что должно быть внутри
      description: Кратко перечислите разделы, команды, ссылки на видео/форумы и т.д.
      placeholder: "1. Кому подходит\n2. Комплектация\n3. Настройка..."
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Источники
      description: Ссылки на документы, посты, видео. Можно прикрепить Outline/Notion, если есть.
  - type: checkboxes
    id: contribute
    attributes:
      label: Готовы помочь с редактированием?
      options:
        - label: Готов(а) подготовить черновик или PR
